export const GET_GEO_LOCATION = 'GET_GEO_LOCATION';
export const SET_GEO_LOCATION = 'SET_GEO_LOCATION';

export const CURRENT_WEATHER_REQUEST = 'CURRENT_WEATHER_REQUEST';
export const CURRENT_WEATHER_RECEIVE = 'CURRENT_WEATHER_RECEIVE';

export const FORECAST_WEATHER_REQUEST = 'FORECAST_WEATHER_REQUEST';
export const FORECAST_WEAHTER_RECEIVE = 'FORECAST_WEAHTER_RECEIVE';

export const SET_ALL_VISIBILITY = 'SET_ALL_VISIBILITY';
export const SET_SINGLE_VISIBILITY = 'SET_SINGLE_VISIBILITY';

